#!/bin/sh


uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tailscale[-1]
	add ucitrack tailscale
	set ucitrack.@tailscale[-1].init=tailscale
	commit ucitrack
EOF


# 重载 rpcd 服务，以便新安装的界面能顺利显示，否则就必须关闭浏览器重新登录才能显示新安装的界面菜单
/etc/init.d/rpcd reload
exit 0