#!/bin/sh


# Run tailscale for the first time
/etc/init.d/tailscale start
# Enable tailscale at boot
/etc/init.d/tailscale enable

# 重载 rpcd 服务，以便新安装的界面能顺利显示，否则就必须关闭浏览器重新登录才能显示新安装的界面菜单
/etc/init.d/rpcd reload
exit 0